### ISSUE TITLE
integer literal

### ISSUE THREAD

**Issue by sylvainlb** [rdf-ext/rdf-parser-jsonld#1]
I noticed the jsonld parser only accepts strings as literals. I'm wondering if it is correct to use `"x": 50,` instead of `"x": "50"` in json-ld, but I couldn't find the answer in the spec. Do you have the answer?

**Comment by bergos** [comment]
That was a bug in the parser. I fixed it with [this commit](https://github.com/rdf-ext/rdf-parser-jsonld/commit/db43a766083d11086bc4637467e55593afe9686e).

**Comment by sylvainlb** [comment]
nice, thanks!
