### ISSUE TITLE
Cannot use rdf-parser-jsonld

### ISSUE THREAD

**Issue by ValeryIvanov** [rdf-ext/rdf-parser-jsonld#7]
rdf-parser-jsonld is written in new Javascript syntax and this fails in Internet Explorer during development. I cannot build our front end project either, since npm packages are not processed.

This code should be in ES5
https://github.com/rdf-ext/rdf-parser-jsonld/blob/master/lib/ParserStream.js

Read more about this issue here
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

@bergos 
@l00mi

**Comment by bergos** [comment]
Please use the prebuilt versions on the [rdf-ext-dist-builder](http://rdf-ext.zazuko.com/) page if you want the code transpiled to ES5 for the browser. The custom builds are currently not transpiled to ES5. I will try to solve that problem till end of next week. Please also see the [README](https://github.com/rdf-ext/rdf-ext-dist-builder) of the dist-build, how the classes are attached to the `window` object.

**Comment by ValeryIvanov** [comment]
Okay, I did manage to bypass this issue by setting Webpack to transpile those packages with Babel.

I will leave solution here for others

config/paths.js
```
  rdfExt: resolveApp('node_modules/rdf-ext'),
  rdfNormalize: resolveApp('node_modules/rdf-normalize'),
  rdfDatasetSimple: resolveApp('node_modules/rdf-dataset-simple'),
  rdfParserJsonLd: resolveApp('node_modules/rdf-parser-jsonld'),
  rdfSink: resolveApp('node_modules/rdf-sink'),
```

config/webpack.config.dev.js
config/webpack.config.prod.js

```
          // Process JS with Babel.
          {
            test: /\.(js|jsx)$/,
            include: [
                paths.appSrc,
                paths.rdfExt,
                paths.rdfNormalize,
                paths.rdfDatasetSimple,
                paths.rdfParserJsonLd,
                paths.rdfSink,
            ],
            loader: require.resolve('babel-loader'),
            options: {
              
              // This is a feature of `babel-loader` for webpack (not Babel itself).
              // It enables caching results in ./node_modules/.cache/babel-loader/
              // directory for faster rebuilds.
              cacheDirectory: true,
            },
          },
```

I guess it would still be nice to have them in ES5 format to not slow down builds.
